primary: MXF
instruments:
  MXF:
    kind: futures
    group: MXF
    key: MXFR1
    multiplier_twd_per_point: 50
    tick_size: 1
  TXF:
    kind: futures
    group: TXF
    key: TXFR1
    multiplier_twd_per_point: 200
    tick_size: 1
  TMF:
    kind: futures
    group: TMF
    key: TMFR1
    multiplier_twd_per_point: 10
    tick_size: 1
watch_stocks:
  - "2330"
  - "2317"
  - "2454"
